services:
  app:
    build: .
    container_name: items_app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: crud_db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: items_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: crud_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d crud_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: